Resources:
  RDSInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      DBInstanceIdentifier: liveleads-rds-${self:provider.stage}
      DBName: ${self:provider.environment.DB_NAME}
      MasterUsername: ${self:provider.environment.DB_USERNAME}
      MasterUserPassword: ${self:provider.environment.DB_PASSWORD}
      Engine: postgres
      EngineVersion: "16.3"
      DBInstanceClass: db.t3.micro
      AllocatedStorage: "20"
      PubliclyAccessible: true
  RDSSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      SecretString: '{"username":"${self:provider.environment.DB_USERNAME}", "password":"${self:provider.environment.DB_PASSWORD}"}'
