service: chattransfer
frameworkVersion: '>=3.0.0 <4.0.0'


plugins:
  - serverless-esbuild
  - serverless-step-functions

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-1
  stage: ${self:custom.currentStage}
  timeout: 900
  iam:
    ${file(./serverless.role.yml)}
  httpApi:
    cors: true
  environment:
    ${file(./serverless.env.yml):${self:provider.stage}.variables}
custom:
  defaultStage: dev
  currentStage: ${opt:stage, self:custom.defaultStage}
  serverlessPluginTypescript:
    tsConfigFileLocation: './tsconfig.json'
  esbuild:
    config: ./esbuild.config.js
  s3:
    liveLeadsDocumentsBucketName: live-leads-bucket-${self:provider.stage}

functions:
  ${file(./serverless.functions.yml)}
stepFunctions:
  ${file(./serverless.stepFunctions.yml)}

resources:
  - ${file(rdsResources.yml)}
  - ${file(storageResources.yml)}
