Resources:
  LiveLeadsConfigBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: ${self:custom.s3.liveLeadsConfigBucketName}
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
      OwnershipControls:
        Rules:
          - ObjectOwnership: ObjectWriter
  LiveLeadsDocumentsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: ${self:custom.s3.liveLeadsDocumentsBucketName}
      VersioningConfiguration:
        Status: Enabled
