openapi: 3.0.0
info:
  version: "1.0.0"
  title: SendMessage API
  description: API to send a message and receive a response.
servers:
  - url: https://2pjk6m2l37.execute-api.us-east-1.amazonaws.com/dev
paths:
  /chatbot/config:
    get:
      summary: Get all chatbot configurations
      description: Fetches the configuration for all bots.
      responses:
        '200':
          description: Successfully retrieved bot configurations.
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                          format: uuid
                          description: Unique identifier of the bot.
                        name:
                          type: string
                          description: Name of the bot.
                        personalPreamble:
                          type: string
                          description: Personal preamble of the bot.
                          example: You are insurance bot
                        tools:
                          type: array
                          items:
                            type: object
                            properties:
                              id:
                                type: string
                                format: uuid
                                description: Unique identifier of the tool.
                              name:
                                type: string
                                description: Name of the tool.
                              source:
                                type: string
                                nullable: true
                                description: The source file or document linked to the tool, if applicable.
                              tool_schema_properties:
                                type: array
                                items:
                                  type: object
                                  properties:
                                    id:
                                      type: string
                                      format: uuid
                                      description: Unique identifier of the tool schema property.
                                    name:
                                      type: string
                                      description: Name of the schema property.
                                    type:
                                      type: string
                                      description: Type of the schema property (e.g., string, number).
                                    description:
                                      type: string
                                      description: Description of the schema property.
                              type:
                                type: string
                                description: Type of the tool (e.g., FUNCTION, DOCUMENT).
                              description:
                                type: string
                                description: Detailed description of the tool.
                              response:
                                type: string
                                nullable: true
                                description: Default response when using the tool.
        '500':
          description: Server error.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Internal server error"

    post:
      summary: Create or update a bot configuration
      description: Creates a new bot configuration or updates an existing one.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                botName:
                  type: string
                  description: Name of the bot.
                  example: testBot
                personalPreamble:
                  type: string
                  description: Personal preamble of the bot.
                  example: You are insurance bot
                tools:
                  type: array
                  items:
                    type: object
                    properties:
                      name:
                        type: string
                        description: Name of the tool.
                        example: insurance-tool
                      type:
                        type: string
                        description: Tool type (e.g., FUNCTION, DOCUMENT).
                        example: FUNCTION
                      description:
                        type: string
                        description: Detailed description of the tool.
                        example: call when user wants insurance or interested for insurance
                      response:
                        type: string
                        description: Default response for the tool when invoked.
                        example: tell that we will contact to them
                      props:
                        type: array
                        items:
                          type: object
                          properties:
                            name:
                              type: string
                              description: Name of the property.
                              example: householdIncome
                            type:
                              type: string
                              description: Type of the property (e.g., string, boolean, number).
                              example: string
                            description:
                              type: string
                              description: Detailed description of the property.
                              example: household income of customer
              required:
                - botName
                - tools
      responses:
        '200':
          description: Successfully created or updated bot configuration.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Bot configuration successfully created or updated."
        '400':
          description: Invalid input.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Invalid input"
        '500':
          description: Server error.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Internal server error"

  /chatbot/{botName}/config:
    delete:
      summary: Delete a bot configuration
      description: Deletes the configuration for a specific bot by name.
      parameters:
        - in: path
          name: botName
          required: true
          schema:
            type: string
            description: The name of the bot to delete the configuration for.
      responses:
        '200':
          description: Successfully deleted bot configuration.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Bot configuration successfully deleted."
        '400':
          description: Invalid bot name.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Invalid bot name"
        '500':
          description: Server error.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Internal server error"
