openapi: 3.0.0
info:
  version: "1.0.0"
  title: SendMessage API
  description: API to send a message and receive a response.
servers:
  - url: https://17eu8qtll9.execute-api.us-east-1.amazonaws.com/dev
paths:
  /es/send/message:
    post:
      summary: Send a message
      description: Sends a message and receives a response.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - message
                - conversationId
              properties:
                message:
                  type: string
                  description: Text of the message
                conversationId:
                  type: string
                  format: uuid
                  description: ID of the conversation
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: string
  /multilanguage/send/message:
    post:
      summary: Send a message
      description: Sends a message and receives a response.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - message
                - conversationId
              properties:
                message:
                  type: string
                  description: Text of the message
                conversationId:
                  type: string
                  format: uuid
                  description: ID of the conversation
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: string
  /conversation/{conversationId}:
    get:
      summary: Get conversation messages
      description: Retrieves messages from a conversation by its ID.
      parameters:
        - in: path
          name: conversationId
          required: true
          schema:
            type: string
            format: uuid
          description: ID of the conversation
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        type:
                          type: string
                          enum:
                            - HumanMessage
                            - AIMessage
                        content:
                          type: string
                  statusCode:
                    type: integer
                    example: 200
  /message/response:
    post:
      summary: Send a message and create stream to get response by message id
      description: Sends a message with a conversation ID and message ID, initiating a Step Function execution.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                message:
                  type: string
                  description: The message content
                  example: "Hello"
                conversationId:
                  type: string
                  description: The ID of the conversation
                  example: "802202bb-8e0a-4580-81f9-55d7fe4926c0"
                messageId:
                  type: string
                  description: The ID of the message
                  example: "110042ff-3842-4e98-a24c-23779cda0019"
              required:
                - message
                - conversationId
                - messageId
      responses:
        '200':
          description: Step Function initiation response
          content:
            application/json:
              schema:
                type: object
                properties:
                  executionArn:
                    type: string
                    description: The ARN of the Step Function execution
                    example: "arn:aws:states:us-east-1:123456789012:execution:StateMachineName:executionName"
                  startDate:
                    type: string
                    format: date-time
                    description: The start time of the execution
                    example: "2023-08-14T10:10:10.000Z"
        '400':
          description: Invalid request body
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Invalid input"
        '500':
          description: Server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Internal server error"
    get:
      summary: Get message responses from stream
      description: Retrieves an array of message responses filtered by messageId and timestamp.
      parameters:
        - in: query
          name: messageId
          required: true
          schema:
            type: string
            format: uuid
          description: The UUID of the message to filter responses.
          example: "110042ff-3842-4e98-a24c-23779cda0019"
        - in: query
          name: from
          required: true
          schema:
            type: integer
            description: The starting timestamp (in milliseconds since epoch) to filter responses.
            example: 1625192932000
      responses:
        '200':
          description: A list of message responses
          content:
            application/json:
              schema:
                type: object
                properties:
                  message_id:
                    type: string
                    description: The ID of the message
                    example: "110042ff-3842-4e98-a24c-23779cda0019"
                  content:
                    type: string
                    description: The content of the message response
                    example: "This is a response message."
                  timestamp:
                    type: integer
                    description: The timestamp of the response in milliseconds since epoch
                    example: 1625192932000
                  ended:
                    type: boolean
                    description: Is stream ended?
                    example: false

        '400':
          description: Invalid query parameters
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Invalid query parameters"
        '500':
          description: Server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Internal server error"
  /message/{messageId}/response:
    delete:
      summary: Delete a message response
      description: Deletes a specific message response by messageId.
      parameters:
        - in: path
          name: messageId
          required: true
          schema:
            type: string
            format: uuid
          description: The UUID of the message to delete the response for.
          example: "110042ff-3842-4e98-a24c-23779cda0019"
      responses:
        '200':
          description: Message response successfully deleted
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: string
                    description: Confirmation message
                    example: "Message response successfully deleted."
                  statusCode:
                    type: integer
                    description: HTTP status code
                    example: 200
        '400':
          description: Invalid messageId
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Invalid messageId"
        '500':
          description: Server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Internal server error"
