openapi: 3.0.0
info:
  version: "1.0.0"
  title: SendMessage API
  description: API to send a message and receive a response.
servers:
  - url: https://k4jxmf55zi.execute-api.us-east-1.amazonaws.com/send
paths:
  /send/message:
    post:
      summary: Send a message
      description: Sends a message and receives a response.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - message
                - conversationId
              properties:
                message:
                  type: string
                  description: Text of the message
                conversationId:
                  type: string
                  format: uuid
                  description: ID of the conversation
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: string
                    example: "Hello How I can assist you?"
